### ISSUE TITLE
请教一下运行环境

### ISSUE THREAD

**Issue by Gnosnay** [Amano-Sei/MyCSAPPsolution#1]
datalab我最后一题总是pass不了，感觉应该是机器环境的问题，所以想知道您的运行环境是什么🤔

**Comment by Amano-Sei** [comment]
ubuntu 18.04 lts 64位 小端

**Comment by Gnosnay** [comment]
给力 笔芯

**Comment by Gnosnay** [comment]
emmm 再请教一下哈，，
你的datalab 最后一个floatPower2是pass的吗🤔
我这里总是会掉一个死循环

**Comment by Gnosnay** [comment]
最后还是改了makefile 唉。。

**Comment by Amano-Sei** [comment]
我在自己机子上是过了的，然后特地去自己vps上试了下（结果他说可能死循环没过...
这样，你给btest加上-T <time> 参数，如-T 20，设置不让他按照默认的10s超时看看，如果用driver.pl要修改两处的btest参数
至于为什么一个移位的要这么久我也不知道😭

**Comment by Gnosnay** [comment]
极其给力！我也是在vps上试的 最后还是改m64了 谢谢repo主 csapp加油

**Comment by Amano-Sei** [comment]
不用谢，同勉
（小声）顺便问一下，为什么用m64编译就能直接过
另外我还试了单独测试最后一个函数也是秒过，另外我btest源码看不懂😭

**Comment by Gnosnay** [comment]
因为makefile里写的是要求编译出来的可运行目标文件是32位，就是那个`CFLAGS = -O -Wall -m32`，在64位机器上编译的时候，需要依赖一些32位的库。
我就一直怀疑是这个的问题🤔你在一开始编译的时候没有遇到头文件报错说缺少库的问题吗？
补了32位库之后，在VPS上运行最后的测试代码会出各种各样的问题，所以我干脆改成64位了。有点僵硬。。
btest源码我也没有仔细看诶。。对不起。。不过我根据他的使用规则，猜想，既然他要求每次改完`bits.c`都要重新build一遍，说明`btest`是依赖`bits.c`的；然后你看那个`tests.c`，里面有答案的（但是这个答案不能直接用），最后一题是有循环在的；因此我猜想，`btest`是依赖`bits.c`和`test.c`一起build的，然后跑一些用例，比对`bits.c`和`test.c`两者的答案是否一致，这样。。但是没仔细看不能十分确定，，，

> BTW,,我感觉兄弟你睡的有点少啊。。

**Comment by Amano-Sei** [comment]
遇到了，然后百度说装下multilib之后就没放在心上，原来他是32位的支持库么
(之前没仔细看以为test_floatPower2是O(n)，编辑掉了，但是这样更没理由那么久了)
（小声）睡觉7小时已经挺多了😭

**Comment by Gnosnay** [comment]
multilib嘛 看名字是这样的 不过vps上装了这个跑不起来 我docker拉了你的ubuntu版本也跑不起来 可能vps太弱了8。。

testfloatpower具体的代码实现没有仔细看诶 这两天有点忙 有空看一下我们可以再交流哈
还是要多睡点 加油

**Comment by Gnosnay** [comment]
喔对了 另外有一个知乎专栏有没有兴趣一起合写呢？

**Comment by Amano-Sei** [comment]
test_floatPower2的实现是O(log n)的快速幂。
我的vps是ubuntu server lts 18.04 64位 gcc版本是7.3，所以应该不会是因为ubuntu的原因我的电脑可以过。
-m32编译产生的机器代码貌似是fpu版本的，貌似这个指令集很慢。但是我没有系统学过汇编，对汇编的了解仅限于从csapp第三章学到的东西。本来想仔细扒一下，但是我刚刚才找到fpu的教程，不过修改了-T参数后没有超时就说明应该不存在死循环。
明天如果有时间会简单过下教程，然后理解下fpu版本的机器代码，不过不出意外应该不会有什么发现（只是为了学习下32位汇编）
之前我说单独测试floatPower2秒过大概是输错名字了...可以确定就是卡在他上面了。
最后，感谢邀请，但是说实话我自己对这个datalab并说不上所有的地方都明白了，抱歉。

**Comment by Gnosnay** [comment]
输错名字哈哈哈
扒的很仔细了，，决定想先放一下 再去考虑这个问题
加油 ～

**Comment by DayChan** [comment]
这里应该不是移位久，而是它测试时他正确版本的函数执行的慢

**Comment by Amano-Sei** [comment]
他正确版本的函数是快速幂，不知道你想表达的是什么意思。

**Comment by Amano-Sei** [comment]
> 这里应该不是移位久，而是它测试时他正确版本的函数执行的慢

~~他正确版本的函数是快速幂，不知道你想表达的是什么意思。~~
他正确版本的函数是快速幂，，当时猜测的理由就是fpu指令集比较慢。
但是一是年代久远我记不清了，二是这个问题没什么意义，三是“正确版本的函数执行的慢”不是和我说的一个意思么，最近怼莫名其妙的人怼多了，起先话有点冲抱歉。

```cpp
unsigned test_floatPower2(int x) {
  float result = 1.0;
  float p2 = 2.0;
  int recip = (x < 0);
  /* treat tmin specially */
  if ((unsigned)x == 0x80000000) {
      return 0;
  }
  if (recip) {
    x = -x;
    p2 = 0.5;
  }
  while (x > 0) {
    if (x & 0x1)
      result = result * p2;
    p2 = p2 * p2;
    x >>= 1;
  }
  return f2u(result);
}
```

**Comment by DayChan** [comment]
> > 这里应该不是移位久，而是它测试时他正确版本的函数执行的慢
> 
> ~他正确版本的函数是快速幂，不知道你想表达的是什么意思。~
> 他正确版本的函数是快速幂，，当时猜测的理由就是fpu指令集比较慢。
> 但是一是年代久远我记不清了，二是这个问题没什么意义，三是“正确版本的函数执行的慢”不是和我说的一个意思么，最近怼莫名其妙的人怼多了，起先话有点冲抱歉。
> 
> ```c++
> unsigned test_floatPower2(int x) {
>   float result = 1.0;
>   float p2 = 2.0;
>   int recip = (x < 0);
>   /* treat tmin specially */
>   if ((unsigned)x == 0x80000000) {
>       return 0;
>   }
>   if (recip) {
>     x = -x;
>     p2 = 0.5;
>   }
>   while (x > 0) {
>     if (x & 0x1)
>       result = result * p2;
>     p2 = p2 * p2;
>     x >>= 1;
>   }
>   return f2u(result);
> }
> ```

其实我们自己实现的答案只需要一次判断和移位就可以得出答案，它的测试函数要2倍logN次乘法加logN次移位，慢几十倍加上指令集慢超时是正常的。只能说他的超时T设置的没兼顾好

**Comment by Amano-Sei** [comment]
> 其实我们自己实现的答案只需要一次判断和移位就可以得出答案，它的测试函数要2倍logN次乘法加logN次移位，慢几十倍加上指令集慢超时是正常的。只能说他的超时T设置的没兼顾好

说实话，就算是指令集慢和指令执行数高几十倍，这里超时10s都不正常~~就算是多执行1亿倍的指令都不该超时~~。指令集慢终究只是说服我自己不再看这个问题的原因，阁下如果有兴趣可以仔细探究下这个问题。
~~前面想都没想就写出了时间复杂度高x倍这种话，我是傻子~~
~~作为算法结果的验证，写一个时间复杂度稍高的一定正确的算法是很常见的。~~

**Comment by DayChan** [comment]
> > 其实我们自己实现的答案只需要一次判断和移位就可以得出答案，它的测试函数要2倍logN次乘法加logN次移位，慢几十倍加上指令集慢超时是正常的。只能说他的超时T设置的没兼顾好
> 
> 说实话，就算是指令集慢和指令执行数高几十倍，这里超时10s都不正常~就算是多执行1亿倍的指令都不该超时~。指令集慢终究只是说服我自己不再看这个问题的原因，阁下如果有兴趣可以仔细探究下这个问题。
> ~前面想都没想就写出了时间复杂度高x倍这种话，我是傻子~
> ~作为算法结果的验证，写一个时间复杂度稍高的一定正确的算法是很常见的。~

这里的验证是在int范围内进行验证，需要进行接近43亿次的调用呢

**Comment by Amano-Sei** [comment]
> 这里的验证是在int范围内进行验证，需要进行接近43亿次的调用呢

~~我真的巨讨厌张口就来的人~~不过不可否认的是我因为这个问题年代久远又没什么意义，加上最近忙于考研确实很不耐烦。
首先这里进行了6000004次的调用，如果当真有43亿次，那么即使是"我们的"实现一样很可能超时10s。
然后这样吧，晚点我好好看一下并测试下问题到底出在哪，定给您关于这个问题一个满意的答复。
不过我更新gcc版本到9.3.0后并不需要修改超时时间即可通过，~~虽然出现了一个奇怪的bug~~
